/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as FrontendLanguagesIndexImport } from './routes/frontend-languages/index'
import { Route as FrameworksIndexImport } from './routes/frameworks/index'
import { Route as CodeEditorsIndexImport } from './routes/code-editors/index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const FrontendLanguagesIndexRoute = FrontendLanguagesIndexImport.update({
  id: '/frontend-languages/',
  path: '/frontend-languages/',
  getParentRoute: () => rootRoute,
} as any)

const FrameworksIndexRoute = FrameworksIndexImport.update({
  id: '/frameworks/',
  path: '/frameworks/',
  getParentRoute: () => rootRoute,
} as any)

const CodeEditorsIndexRoute = CodeEditorsIndexImport.update({
  id: '/code-editors/',
  path: '/code-editors/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/code-editors/': {
      id: '/code-editors/'
      path: '/code-editors'
      fullPath: '/code-editors'
      preLoaderRoute: typeof CodeEditorsIndexImport
      parentRoute: typeof rootRoute
    }
    '/frameworks/': {
      id: '/frameworks/'
      path: '/frameworks'
      fullPath: '/frameworks'
      preLoaderRoute: typeof FrameworksIndexImport
      parentRoute: typeof rootRoute
    }
    '/frontend-languages/': {
      id: '/frontend-languages/'
      path: '/frontend-languages'
      fullPath: '/frontend-languages'
      preLoaderRoute: typeof FrontendLanguagesIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/code-editors': typeof CodeEditorsIndexRoute
  '/frameworks': typeof FrameworksIndexRoute
  '/frontend-languages': typeof FrontendLanguagesIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/code-editors': typeof CodeEditorsIndexRoute
  '/frameworks': typeof FrameworksIndexRoute
  '/frontend-languages': typeof FrontendLanguagesIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/code-editors/': typeof CodeEditorsIndexRoute
  '/frameworks/': typeof FrameworksIndexRoute
  '/frontend-languages/': typeof FrontendLanguagesIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/code-editors' | '/frameworks' | '/frontend-languages'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/code-editors' | '/frameworks' | '/frontend-languages'
  id:
    | '__root__'
    | '/'
    | '/code-editors/'
    | '/frameworks/'
    | '/frontend-languages/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CodeEditorsIndexRoute: typeof CodeEditorsIndexRoute
  FrameworksIndexRoute: typeof FrameworksIndexRoute
  FrontendLanguagesIndexRoute: typeof FrontendLanguagesIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CodeEditorsIndexRoute: CodeEditorsIndexRoute,
  FrameworksIndexRoute: FrameworksIndexRoute,
  FrontendLanguagesIndexRoute: FrontendLanguagesIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/code-editors/",
        "/frameworks/",
        "/frontend-languages/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/code-editors/": {
      "filePath": "code-editors/index.tsx"
    },
    "/frameworks/": {
      "filePath": "frameworks/index.tsx"
    },
    "/frontend-languages/": {
      "filePath": "frontend-languages/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
